title: My Personal Site
author: Biswitha Reddy
email: biswithareddy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Interested in reading books and playing games.

# social links
twitter_username: biswithareddy # DO NOT include the @ character, or else the build will fail!
github_username:  biswithareddy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
